### ISSUE TITLE
Initial implementation tracker

### ISSUE THREAD

**Issue by paulshen** [paulshen/bs-discord#1]
## Known TODOs

- [ ] [Permissions](https://discordapp.com/developers/docs/topics/permissions)
- [ ] [OAuth2](https://discordapp.com/developers/docs/topics/oauth2)
- [ ] [Missing heartback ack](https://discordapp.com/developers/docs/topics/gateway#heartbeating-example-gateway-heartbeat-ack)
- [ ] [Rate limits](https://discordapp.com/developers/docs/topics/rate-limits)
- [ ] [Sharding](https://discordapp.com/developers/docs/topics/gateway#sharding)
- [ ] [All gateway commands](https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-commands)
- [ ] [Handle all gateway events](https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-events)
- [ ] [Get gateway](https://discordapp.com/developers/docs/topics/gateway#get-gateway)
- [ ] [Gateway close codes](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes)
- [ ] [Voice connections](https://discordapp.com/developers/docs/topics/voice-connections)
- [ ] [HTTP response codes](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#http-http-response-codes)
- [ ] [JSON response codes](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#json)
- [ ] [RPC](https://discordapp.com/developers/docs/topics/rpc)

### Resources
- [ ] [Audit log](https://discordapp.com/developers/docs/resources/audit-log)
- [ ] [Channel](https://discordapp.com/developers/docs/resources/channel)
- [ ] [Emoji](https://discordapp.com/developers/docs/resources/emoji)
- [ ] [Guild](https://discordapp.com/developers/docs/resources/guild)
- [ ] [Invite](https://discordapp.com/developers/docs/resources/invite)
- [ ] [User](https://discordapp.com/developers/docs/resources/user)
- [ ] [Voice](https://discordapp.com/developers/docs/resources/voice)
- [ ] [Webhook](https://discordapp.com/developers/docs/resources/webhook)
